/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWord */

#ifndef _Included_HelloWord
#define _Included_HelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWord
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWord_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
